### ISSUE TITLE
Several ERRORS from TypeScript engine

### ISSUE THREAD

**Issue by pavel-kolesnikov** [lucacasonato/rethinkdb-deno#4]
```
PS C:\Users\user\Documents\works\deno\tms\deno-app> deno run -A .\main.ts
Check file:///C:/Users/user/Documents/works/deno/tms/deno-app/main.ts
error: TS7022 [ERROR]: 'query' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
  get query() {
      ~~~~~
    at https://deno.land/x/rethinkdb@0.1.0/internal/r/function.ts:18:7

TS7023 [ERROR]: 'query' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
  get query() {
      ~~~~~
    at https://deno.land/x/rethinkdb@0.1.0/internal/r/function.ts:18:7

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'. 
export { Session, SessionImpl } from "./internal/session.ts";
         ~~~~~~~
    at https://deno.land/x/rethinkdb@0.1.0/mod.ts:1:10

Found 3 errors.
```

The `main.ts`:
```TypeScript
import { r, connect } from "https://deno.land/x/rethinkdb@0.1.0/mod.ts";

const session = await connect({ hostname: 'localhost', port: 28015 })
await r.db('test').tableCreate('tv_shows').run(session)

const res = await r.db('test').table('tv_shows').insert({ name: 'Star Trek TNG' }).run(session)
console.log(res)
```

**Comment by pavel-kolesnikov** [comment]
Sorry, I've started to learn deno today and got these errors. This is the single library for rethinkdb in deno lands that seems to work...
